# Tables notebook

For all of the lower notebooks I have a graphs being ran in them and am choosing to not show the table to save space

Here is where I will show it instead

In [1]:
import pandas as pd
import numpy as np

url = "https://raw.githubusercontent.com/hankike/Premier_Prediction/refs/heads/main/data/cleaned_premier.csv"

## Results table

This table resides in `01records.ipynb`

In [2]:
import sys
from pathlib import Path

sys.path.append(str(Path.cwd().parent))

from src.tables import create_results_table

In [3]:
results = create_results_table(url)

results

                Team  Wins  Losses  Draws  Games
0            Arsenal   154      56     56    266
1        Aston Villa   114      99     53    266
6            Chelsea   123      77     66    266
4           Brighton    90      89     87    266
7     Crystal Palace    82     103     81    266
8            Everton    86     110     70    266
26          West Ham    91     114     61    266
27            Wolves    81     124     61    266
16        Man United   127      74     65    266
17         Newcastle   107      96     63    266
15          Man City   182      41     43    266
13         Liverpool   165      43     58    266
23         Tottenham   115      99     52    266
3          Brentford    68      73     49    190
21       Southampton    44     106     40    190
5            Burnley    41      98     51    190
2        Bournemouth    61      78     51    190
12         Leicester    67      85     38    190
9             Fulham    63      83     44    190
11             Leeds    45      67     40    152
19     Nott'm Forest    48      65     39    152
20  Sheffield United    24      69     21    114
24           Watford    14      47     15     76
18           Norwich    10      53     13     76
10           Ipswich     4      24     10     38
14             Luton     6      24      8     38
22        Sunderland    14      12     12     38
25         West Brom     5      22     11     38

## Standings table

This table resides in `02win_percentage.ipynb`

In [4]:
import sys
from pathlib import Path

sys.path.append(str(Path.cwd().parent))

from src.tables import create_standings_table

In [5]:
standings = create_standings_table(url)

standings

,Team,Home Games,Home Win Percentage,Home Point Percentage,Road Games,Road Win Percentage,Road Point Percentage
15,Man City,133,0.759,0.895,133,0.609,0.797
13,Liverpool,133,0.714,0.910,133,0.526,0.767
0,Arsenal,133,0.647,0.835,133,0.511,0.744
16,Man United,133,0.556,0.767,133,0.398,0.677
23,Tottenham,133,0.519,0.647,133,0.346,0.609
1,Aston Villa,133,0.504,0.707,133,0.353,0.549
6,Chelsea,133,0.489,0.767,133,0.436,0.654
17,Newcastle,133,0.489,0.737,133,0.316,0.541
22,Sunderland,19,0.474,0.789,19,0.263,0.579
12,Leicester,95,0.411,0.579,95,0.295,0.526
3,Brentford,95,0.411,0.716,95,0.305,0.516
9,Fulham,95,0.389,0.579,95,0.274,0.547
26,West Ham,133,0.383,0.639,133,0.301,0.504
4,Brighton,133,0.368,0.722,133,0.308,0.609
27,Wolves,133,0.361,0.571,133,0.248,0.496
8,Everton,133,0.361,0.617,133,0.286,0.556
2,Bournemouth,95,0.347,0.663,95,0.295,0.516
19,Nott'm Forest,76,0.342,0.658,76,0.289,0.487
11,Leeds,76,0.342,0.645,76,0.250,0.474
7,Crystal Palace,133,0.331,0.669,133,0.286,0.556
20,Sheffield United,57,0.298,0.439,57,0.123,0.351
21,Southampton,95,0.242,0.463,95,0.221,0.421
5,Burnley,95,0.221,0.505,95,0.211,0.463
24,Watford,38,0.211,0.421,38,0.158,0.342
14,Luton,19,0.211,0.421,19,0.105,0.316
18,Norwich,38,0.184,0.342,38,0.079,0.263
25,West Brom,19,0.158,0.474,19,0.105,0.368
10,Ipswich,19,0.053,0.263,19,0.158,0.474